// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzpkuE3zDGiO8uEXYmOhcQHkaLRS_PyLw',
    appId: '1:869880772082:web:2e8624b8145a717f86e76b',
    messagingSenderId: '869880772082',
    projectId: 'event-app-99d62',
    authDomain: 'event-app-99d62.firebaseapp.com',
    storageBucket: 'event-app-99d62.firebasestorage.app',
    measurementId: 'G-BL6FYR0F37',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmuF_Pl0ZFZQrNVnRpp19hG1lKixGWQWU',
    appId: '1:869880772082:android:01fad5a91f9ad63e86e76b',
    messagingSenderId: '869880772082',
    projectId: 'event-app-99d62',
    storageBucket: 'event-app-99d62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ9s_-YLvb-9yi23uqMy_IIUTFV_M3_qc',
    appId: '1:869880772082:ios:b414b4f3b8ddc67486e76b',
    messagingSenderId: '869880772082',
    projectId: 'event-app-99d62',
    storageBucket: 'event-app-99d62.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZ9s_-YLvb-9yi23uqMy_IIUTFV_M3_qc',
    appId: '1:869880772082:ios:b414b4f3b8ddc67486e76b',
    messagingSenderId: '869880772082',
    projectId: 'event-app-99d62',
    storageBucket: 'event-app-99d62.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzpkuE3zDGiO8uEXYmOhcQHkaLRS_PyLw',
    appId: '1:869880772082:web:33b398ef79ca9ae886e76b',
    messagingSenderId: '869880772082',
    projectId: 'event-app-99d62',
    authDomain: 'event-app-99d62.firebaseapp.com',
    storageBucket: 'event-app-99d62.firebasestorage.app',
    measurementId: 'G-BEHKD5P1F9',
  );
}
